Repository MinWonHaeSo/ESC_CLIENT, pull requests merged in 2022-12, with the labels that each got.

#40 Feat : Rental Item List 업로드 구현
  .env
  .gitignore
  index.html
  package.json
  src/components/Stardium/StardiumEdit.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditAddress.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditImage.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditImageList.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditInput.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditRentalItem.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditRentalItemList.tsx
  src/components/Stardium/StardiumEditElements/StardiumRentalItem.tsx
  src/components/common/RentalItemList.tsx
  src/hooks/useKakaoMapScript.ts
  src/store/stardiumWriteSlice.ts
  src/store/store.ts
  vite.config.ts
  yarn.lock
Labels: 🚀 Feature

#47 Refactor : store에 연결된 slice 내부 코드 수정
  src/components/Header/Header.tsx
  src/components/Header/Navbar.tsx
  src/components/SearchPassword/EnterNewPassWord.tsx
  src/components/SearchPassword/EnterValidateCode.tsx
Labels: 🔨 Refactor

#52 Feat : 체육관 등록, 검색, 지도 표시 작업
  .env~530a4920889104786fe84c9c6cb9f565b1eb6162
  src/App.tsx
  src/api/baseApi.ts
  src/api/fileUpload.ts
  src/api/stardiumApi.ts
  src/api/userApi.ts
  src/components/Home/BasicUserHome.tsx
  src/components/Home/ManagerUserHome.tsx
  src/components/KakaoMap/Map.tsx
  src/components/Stardium/MarkerStadiumInfo.tsx
  src/components/Stardium/StardiumEdit.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditAddress.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditImage.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditImageList.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditRentalItem.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditRentalItemList.tsx
  src/components/Stardium/StardiumEditElements/StardiumEditTag.tsx
  src/components/Stardium/StardiumEditElements/StardiumTime.tsx
  src/components/Stardium/StardiumSearch.tsx
  src/constants/defaultLocation.ts
  src/constants/path.ts
  src/context/OriginFilesContext.tsx
  src/hooks/useCurrentLocation.ts
  src/hooks/useDefaultTime.ts
  src/hooks/useKakaoMapScript.ts
  src/hooks/useThrottleRef.ts
  src/lib/utils/fileObjectToIdUrlFile.ts
  src/pages/Homepage.tsx
  src/service/kakaoMapService.ts
  src/store/stardiumSlice.ts
  src/store/stardiumWriteSlice.ts
Labels: 🚀 Feature

#54 Fix : Merge 충돌
  src/App.tsx
  src/api/baseApi.ts
  src/api/userApi.ts
  src/components/OAuth/OAuthRedirect.tsx
  src/constants/path.ts
  src/store/authSlice.ts
Labels: 🐛 Bug

#67 Feat : Reservation Page 작업 (step1, step2)
  src/App.tsx
  src/api/reservationApi.ts
  src/api/stadiumApi.ts
  src/components/Review/Review.tsx
  src/components/Review/ReviewDropdown.tsx
  src/components/Stadium/EditElements/EditRentalItem.tsx
  src/components/Stadium/EditElements/EditRentalItemList.tsx
  src/components/Stadium/EditElements/EditTag.tsx
  src/components/Stadium/EditElements/EditTime.tsx
  src/components/Stadium/StadiumEdit.tsx
  src/components/StadiumDetail/Detail.tsx
  src/components/StadiumDetail/Info.tsx
  src/components/StadiumReservation/Reservation.tsx
  src/components/StadiumReservation/ReservationAccordion.tsx
  src/components/StadiumReservation/ReservationButton.tsx
  src/components/StadiumReservation/ReservationDate.tsx
  src/components/StadiumReservation/ReservationItem.tsx
  src/components/StadiumReservation/ReservationPerson.tsx
  src/components/StadiumReservation/ReservationPrevStepButton.tsx
  src/components/StadiumReservation/ReservationRentalItem.tsx
  src/components/StadiumReservation/ReservationRentalList.tsx
  src/components/StadiumReservation/ReservationStepOne.tsx
  src/components/StadiumReservation/ReservationStepThree.tsx
  src/components/StadiumReservation/ReservationStepTwo.tsx
  src/components/StadiumReservation/ReservationTime.tsx
  src/components/StadiumReservation/TImeSelectList.tsx
  src/components/StadiumReservation/TimeSelectItem.tsx
  src/components/common/CustomDate.tsx
  src/components/common/CustomTime.tsx
  src/components/common/Dividers.tsx
  src/components/common/StepComponentProcess.tsx
  src/hooks/useCurrentLocation.ts
  src/hooks/useThrottleRef.ts
  src/lib/utils/excludeTimes.ts
  src/lib/utils/formatter.ts
  src/lib/utils/intlFormatter.ts
  src/pages/StadiumReservation.tsx
  src/pages/StadiumReservationPage.tsx
  src/routes/PrivateRoutes.tsx
  src/store/stadiumMarkerSlice.ts
  src/store/stadiumReservationSlice.ts
  src/store/stadiumWriteSlice.ts
  src/store/store.ts
Labels: 🚀 Feature

#68 FIx : typo
  src/App.tsx
  src/constants/path.ts
Labels: 🐛 Bug

#71 Feat : Modal Provider
  src/App.tsx
  src/Portal/Portal.tsx
  src/api/reservationApi.ts
  src/api/stadiumApi.ts
  src/components/MainManager/ManagerUserHome.tsx
  src/components/Modal/Modal.tsx
  src/components/StadiumReservation/ReservationDate.tsx
  src/constants/path.ts
  src/context/ModalContext.tsx
  src/store/stadiumReservationSlice.ts
Labels: 🚀 Feature

#72 Fix : Modal export default
  src/App.tsx
  src/context/ModalContext.tsx
Labels: 🐛 Bug

#73 Refactor : EmptyItemNotification 추상화 작업
  src/api/stadiumApi.ts
  src/components/CardStadium/CardStadium.tsx
  src/components/MainBasicUser/MarkerStadiumInfo.tsx
  src/components/MeLikeStadium/MeLikeStadium.tsx
  src/components/MeRecentSearch/MeRecentSearch.tsx
  src/components/common/EmptyItemNotification.tsx
  src/routes/Layout.tsx
Labels: 🔨 Refactor

#76 Feat : Review, Reservation 사용자 검증 처리
  src/api/reviewApi.ts
  src/components/Review/Review.tsx
  src/components/Review/ReviewDropdown.tsx
  src/components/Review/ReviewList.tsx
  src/components/Review/ReviewListItem.tsx
  src/components/Review/ReviewSubmit.tsx
  src/components/StadiumDetail/Detail.tsx
  src/components/StadiumDetail/UserActionButton.tsx
  src/components/StadiumReservation/ReservationAccordion.tsx
  src/components/StadiumReservation/ReservationStepOne.tsx
  src/components/StadiumReservation/TimeSelectItem.tsx
  src/components/common/StarRate.tsx
  src/hooks/useInfinityScroll.tsx
  src/lib/utils/formatter.ts
  src/store/stadiumReview.ts
  src/store/stadiumWriteSlice.ts
Labels: 🚀 Feature

#77 Feat : 예약 내역 상세보기 및 예약 결제 세 번째 단계 UI 구현 완료
  src/App.tsx
  src/Portals/Modal.tsx
  src/Portals/Portal.tsx
  src/api/authApi.ts
  src/api/baseApi.ts
  src/api/reservationApi.ts
  src/api/stadiumApi.ts
  src/components/CardStadium/CardStadium.tsx
  src/components/Header/Header.tsx
  src/components/Login/LoginForm.tsx
  src/components/MeInfo/MeInfoDetail.tsx
  src/components/MeLikeStadium/MeLikeStadium.tsx
  src/components/MeRentalList/MeRentalStadium.tsx
  src/components/MeRentalList/MeRentalStadiumDetailModal.tsx
  src/components/Modal/Modal.tsx
  src/components/StadiumReservation/ReservationAccordion.tsx
  src/components/StadiumReservation/ReservationButton.tsx
  src/components/StadiumReservation/ReservationDate.tsx
  src/components/StadiumReservation/ReservationPerson.tsx
  src/components/StadiumReservation/ReservationPrevStepButton.tsx
  src/components/StadiumReservation/ReservationRentalItem.tsx
  src/components/StadiumReservation/ReservationRentalList.tsx
  src/components/StadiumReservation/ReservationStepOne.tsx
  src/components/StadiumReservation/ReservationStepThree.tsx
  src/components/StadiumReservation/ReservationStepThree/ReservationInfo.tsx
  src/components/StadiumReservation/ReservationStepThree/ReservationPayment.tsx
  src/components/StadiumReservation/ReservationStepThree/ReservationProfile.tsx
  src/components/StadiumReservation/ReservationStepThree/ReservationRentalItemList.tsx
  src/components/StadiumReservation/ReservationStepThree/StyledSerparateLine.tsx
  src/components/StadiumReservation/ReservationStepThree/ToggleButton.tsx
  src/components/StadiumReservation/ReservationStepTwo.tsx
  src/components/StadiumReservation/ReservationTime.tsx
  src/components/StadiumReservation/TImeSelectList.tsx
  src/components/common/InsertImage.tsx
  src/context/ModalContext.tsx
  src/lib/utils/accessStadium.ts
  src/store/authSlice.ts
  src/store/stadiumReservationSlice.ts
  src/store/store.ts
Labels: 🚀 Feature

#80 Feat : 알림내역, 예약 및 결제 API 연동 완료
  src/api/authApi.ts
  src/api/notificationApi.ts
  src/api/reservationApi.ts
  src/api/stadiumApi.ts
  src/components/Header/Header.tsx
  src/components/Header/Navbar.tsx
  src/components/Header/NotificationButton.tsx
  src/components/MeLikeStadium/MeLikeStadium.tsx
  src/components/MeRecentSearch/MeRecentSearch.tsx
  src/components/MeRentalList/MeRentalList.tsx
  src/components/MeRentalList/MeRentalStadium.tsx
  src/components/MeRentalList/MeRentalStadiumDetailModal.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/NotificationList.tsx
  src/components/Notification/NotificationTab.tsx
  src/components/Review/ReviewHeader.tsx
  src/components/SearchPassword/EnterValidateCode.tsx
  src/components/SearchPassword/SearchPassWordProcess.tsx
  src/components/SearchPassword/SearchPassword.tsx
  src/components/SearchPassword/ValidateEmail.tsx
  src/components/StadiumReservation/ReservationButton.tsx
  src/components/StadiumReservation/ReservationDate.tsx
  src/components/StadiumReservation/ReservationRentalItem.tsx
  src/components/StadiumReservation/ReservationRentalList.tsx
  src/components/StadiumReservation/ReservationStepOne.tsx
  src/components/StadiumReservation/ReservationStepThree.tsx
  src/components/StadiumReservation/ReservationStepThree/Radio.tsx
  src/components/StadiumReservation/ReservationStepThree/ReservationInfo.tsx
  src/components/StadiumReservation/ReservationStepThree/ReservationPayment.tsx
  src/components/StadiumReservation/ReservationStepThree/ReservationRentalItemList.tsx
  src/components/StadiumReservation/ReservationStepTwo.tsx
  src/components/StadiumReservation/TImeSelectList.tsx
  src/components/common/Dividers.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/ScrollToTopButton.tsx
  src/constants/path.ts
  src/pages/StadiumReservationPage.tsx
  src/store/searchPassWordSlice.ts
  src/store/stadiumReservationSlice.ts
Labels: 🚀 Feature

#81 Feat : Manager Stadium Upload List UI 작업
  src/App.tsx
  src/api/stadiumApi.ts
  src/components/MainBasicUser/MainBasicUser.tsx
  src/components/MainBasicUser/MarkerStadiumInfo.tsx
  src/components/ManagerStadiumList/ManagerStadiumList.tsx
  src/constants/headerNav.ts
  src/constants/path.ts
  src/pages/ManagerStadiumListPage.tsx
  src/pages/StadiumListPage.tsx
  src/store/pagingSlice.ts
  src/store/store.ts
Labels: 🚀 Feature

#86 Feat : 체육관 예약 유저 상세 정보 작업
  src/App.tsx
  src/api/stadiumApi.ts
  src/components/ManagerStadiumList/ManagerStadiumList.tsx
  src/components/MeLikeStadium/MeLikeStadium.tsx
  src/components/ReservationUserInfo/ReservationUserInfo.tsx
  src/components/ReservationUserInfo/ReservationUserInfoItem.tsx
  src/components/ReservationUserInfo/ReservationUserInfoList.tsx
  src/components/ReservationUserInfo/ReservationUserInfoModal.tsx
  src/constants/path.ts
  src/pages/ReservationUserInfoPage.tsx
Labels: 🚀 Feature

#87 Feat : 체육관 예약 상세 정보 페이지 작업
  src/components/MainBasicUser/MainBasicUser.tsx
  src/components/ManagerStadiumList/ManagerStadiumList.tsx
  src/components/ReservationUserInfo/PrevButton.tsx
  src/components/ReservationUserInfo/ReservationUserInfo.tsx
  src/components/Stadium/EditElements/EditRentalItemList.tsx
  src/components/StadiumReservation/ReservationItem.tsx
  src/components/StadiumReservation/ReservationStepOne.tsx
  src/components/StadiumReservation/ReservationStepOne/ReservationAccordion.tsx
  src/components/StadiumReservation/ReservationStepOne/ReservationDate.tsx
  src/components/StadiumReservation/ReservationStepOne/ReservationPerson.tsx
  src/components/StadiumReservation/ReservationStepOne/ReservationTime.tsx
  src/components/StadiumReservation/ReservationStepOne/TImeSelectList.tsx
  src/components/StadiumReservation/ReservationStepOne/TimeSelectItem.tsx
  src/components/StadiumReservation/ReservationStepThree.tsx
  src/components/StadiumReservation/ReservationStepThree/ReservationRentalItem.tsx
  src/components/StadiumReservation/ReservationStepTwo.tsx
  src/components/StadiumReservation/ReservationStepTwo/ReservationRentalItemList.tsx
  src/components/StadiumReservation/ReservationStepTwo/ReservationRentalList.tsx
Labels: 🚀 Feature

#88 Feat : 예약내역, 알림내역, 찜한 체육관 내역 페이지네이션 기능 추가
  src/api/authApi.ts
  src/api/baseApi.ts
  src/api/notificationApi.ts
  src/api/reservationApi.ts
  src/api/stadiumApi.ts
  src/api/userApi.ts
  src/components/CardStadium/CardStadium.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/Navbar.tsx
  src/components/Login/Login.tsx
  src/components/MeInfo/MeInfo.tsx
  src/components/MeInfo/MePassword.tsx
  src/components/MeInfo/formValidation.ts
  src/components/MeLikeStadium/MeLikeStadium.tsx
  src/components/MeRecentSearch/MeRecentSearch.tsx
  src/components/MeRentalList/MeRentalList.tsx
  src/components/MeRentalList/MeRentalStadium.tsx
  src/components/MeRentalList/MeRentalStadiumDetailModal.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/NotificationList.tsx
  src/components/Notification/NotificationRead.tsx
  src/components/Notification/NotificationTab.tsx
  src/components/Notification/NotificationUnread.tsx
  src/components/SignOut/SignOut.tsx
  src/components/SignUp/Form/Email.tsx
  src/components/SignUp/SignUp.tsx
  src/components/SignUp/SignUpForm.tsx
  src/components/StadiumReservation/ReservationButton.tsx
  src/components/StadiumReservation/ReservationStepThree.tsx
  src/constants/notificationTab.ts
  src/lib/utils/accessStadium.ts
  src/store/authSlice.ts
  src/store/notificationSlice.ts
  src/store/pagingSlice.ts
Labels: 🚀 Feature

#89 fix: typo
  src/components/ManagerStadiumList/ManagerStadiumList.tsx
Labels: 🐛 Bug

#92 Refactor : 메인 컴포넌트 index로 네이밍 변경
  src/api/stadiumApi.ts
  src/components/Review/Index.tsx
  src/components/SearchPassword/Index.tsx
  src/components/SignOut/Index.tsx
  src/components/SignUp/Index.tsx
  src/components/Slide/Index.tsx
  src/components/Stadium/EditElements/EditTag.tsx
  src/components/StadiumDetail/Detail.tsx
  src/components/StadiumReservation/Index.tsx
  src/components/Tag/Index.tsx
  src/pages/SearchPasswordPage.tsx
  src/pages/SignOutPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/StadiumDetailPage.tsx
  src/pages/StadiumReservationPage.tsx
Labels: 🔨 Refactor

#93 Refactor : main 브랜치에 배포하기 위한 yml 파일 수정
  .github/workflows/deploy.yml
Labels: 🔨 Refactor

#96 Fix : 대문자 오탈자 수정
  src/assets/spinner.gif
Labels: 🐛 Bug

#100 Feat : reveiw, rental 추가 API 작업
  src/api/reviewApi.ts
  src/api/stadiumApi.ts
  src/components/MainBasicUser/MarkerStadiumInfo.tsx
  src/components/ManagerStadiumList/Index.tsx
  src/components/ManagerStadiumList/StadiumList.tsx
  src/components/ReservationUserInfo/Index.tsx
  src/components/ReservationUserInfo/ReservationUserInfoItem.tsx
  src/components/ReservationUserInfo/ReservationUserInfoList.tsx
  src/components/ReservationUserInfo/ReservationUserInfoModal.tsx
  src/components/Review/Index.tsx
  src/components/Review/ReviewList.tsx
  src/components/Review/ReviewListItem.tsx
  src/components/Review/ReviewSubmit.tsx
  src/pages/ReservationUserInfoPage.tsx
  src/store/pagingSlice.ts
  src/store/stadiumReview.ts
Labels: 🔨 Refactor

#102 Refactor : 찜한 체육관 내역 찜하기 해제 기능 리팩토링
  src/api/stadiumApi.ts
  src/components/CardStadium/Index.tsx
  src/components/Header/NotificationButton.tsx
  src/components/MeLikeStadium/Index.tsx
  src/components/StadiumDetail/Detail.tsx
  src/components/StadiumDetail/UserActionButton.tsx
  src/store/pagingSlice.ts
  src/store/stadiumWriteSlice.ts
Labels: 🔨 Refactor

#104 Feat : Stadium Remove API
  src/api/stadiumApi.ts
  src/components/ManagerStadiumList/Index.tsx
  src/components/Stadium/EditElements/EditAddress.tsx
Labels: 🚀 Feature

#107 Refactor : PrivateRoute 주석처리 해제
  src/App.tsx
Labels: 🔨 Refactor

#109 Fix : 권한 체크
  src/components/Review/ReviewSubmit.tsx
  src/components/StadiumDetail/UserActionButton.tsx
Labels: 🐛 Bug

#110 fix : typo
  src/components/ManagerStadiumList/Index.tsx
  src/components/Review/ReviewSubmit.tsx
Labels: 🐛 Bug

#108 Refactor : PrivateRoute 주석처리 해제 (#107)
  src/App.tsx
  src/components/ManagerStadiumList/Index.tsx
  src/components/Review/ReviewSubmit.tsx
  src/components/StadiumDetail/UserActionButton.tsx
Labels: 🔨 Refactor

#111 Fix : API Request toast alert add
  src/components/ManagerStadiumList/Index.tsx
  src/components/Review/ReviewListItem.tsx
Labels: 🐛 Bug

#112 Fix : API 호출 후 Alert창 호출
  src/components/ManagerStadiumList/Index.tsx
  src/components/Review/ReviewListItem.tsx
Labels: 🐛 Bug

#113 Refactor : 소셜 로그인 redirect URI 수정
  src/components/SocialLogin/GoogleSocialLogin.tsx
  src/components/SocialLogin/KakaoSocialLogin.tsx
  src/components/SocialLogin/NaverSocialLogin.tsx
Labels: 🔨 Refactor

#114 Refactor : 소셜 로그인 redirect URI 수정 (#113)
  src/components/SocialLogin/GoogleSocialLogin.tsx
  src/components/SocialLogin/KakaoSocialLogin.tsx
  src/components/SocialLogin/NaverSocialLogin.tsx
Labels: 🔨 Refactor

#115 Fix : Clouninary ios imgae error
  src/components/Stadium/StadiumEdit.tsx
Labels: 🐛 Bug

#117 Fix : 체육관 업로드 리스트 Remove Reducer 작업
  src/api/stadiumApi.ts
  src/components/ManagerStadiumList/Index.tsx
  src/store/pagingSlice.ts
Labels: 🔨 Refactor

#119 Refactor : api '/' 누락
  src/api/authApi.ts
  src/components/ReservationUserInfo/ReservationUserInfoItem.tsx
Labels: 🔨 Refactor

#120 Refactor : '/' 중복 제거
  src/components/SocialLogin/GoogleSocialLogin.tsx
  src/components/SocialLogin/KakaoSocialLogin.tsx
  src/components/SocialLogin/NaverSocialLogin.tsx
Labels: 🔨 Refactor

#121 Refactor : OAuth2 리다이렉트 주소 '/' 중복 제거
  src/api/authApi.ts
  src/components/ReservationUserInfo/ReservationUserInfoItem.tsx
  src/components/SocialLogin/GoogleSocialLogin.tsx
  src/components/SocialLogin/KakaoSocialLogin.tsx
  src/components/SocialLogin/NaverSocialLogin.tsx
Labels: 🔨 Refactor

#122 Refactor : 공통 Type 추상화 및 확장 리팩토링
  src/api/authApi.ts
  src/api/reservationApi.ts
  src/api/reviewApi.ts
  src/api/service.ts
  src/api/stadiumApi.ts
  src/api/userApi.ts
  src/components/MainBasicUser/Index.tsx
  src/components/MainBasicUser/MarkerStadiumInfo.tsx
  src/components/ManagerStadiumList/StadiumList.tsx
  src/components/MeRentalList/MeRentalStadium.tsx
  src/components/MeRentalList/MeRentalStadiumItem.tsx
  src/components/ReservationUserInfo/ReservationUserInfoItem.tsx
  src/components/ReservationUserInfo/ReservationUserInfoList.tsx
  src/store/pagingSlice.ts
  src/store/stadiumMarkerSlice.ts
  src/types/memberType.ts
  src/types/stadiumType.ts
  src/types/userType.ts
Labels: 🔨 Refactor
